### ISSUE TITLE
Changing task status won't affect the framework

### ISSUE THREAD

**Issue by Neefay** [Neefay/Rhea#2]
The current method for changing a task's status will change it in appearance only, not actually counting towards completing the mission.

**Comment by Neefay** [comment]
This might require a change within the task evaluation cycle within the framework itself, we'll see.

**Comment by Coryf88** [comment]
I've looked into this and it looks like the best way to resolve this would indeed be to modify the way the framework's task system works.

Currently, Rhea would have to modify the win/lose condition of the task based on the selected 'Succeeded'/'Failed'. 'Canceled' would have to modify the lose condition and remove the task from primary and secondary.
